### ISSUE TITLE
Karma count not correct. 

### ISSUE THREAD

**Issue by Samanthaschouler** [wilg/headlines#22]
I had a feeling my karma count should have been higher so I added up the first page of my best ones and I was right. I came out way higher. What's up with that?

**Comment by wilg** [comment]
Hi @Samanthaschouler! Your karma count subtracts the number of submissions you've made to prevent people from spamming random suggestions. So it should be the same as the number of votes _other people_ have made on your headlines.

The code for this is here: https://github.com/wilg/headlines/blob/8e03344e6283414ddbc1ffee4037b9904e7b8775/app/models/user.rb#L65-L69
