### ISSUE TITLE
Suggestion: Copy Feature

### ISSUE THREAD

**Issue by fauxreport** [wilg/headlines#23]
Hey Wil, 
I love Headline Smasher! I think that adding a copy feature would make it even better. I use it for my website, and a copy feature would save a little time. Thanks!
From,
The Faux Report
[Website](https://thefauxreport.com)

**Comment by wilg** [comment]
Are you just copying Headline Smasher headlines onto your own site? That doesn't seem very ethical (or interesting). At a minimum, you should link to the headline page on headlinesmasher.com if you are going to use it.
